### ISSUE TITLE
saving design and loadDesign doesn't work as expected

### ISSUE THREAD

**Issue by naczu** [unlayer/react-email-editor#107]
After saving design as json to database, it doesn't load json design properly.

**Comment by adeelraza** [comment]
@naczu Please make sure the JSON encoding is not messed up. This normally happens when you save JSON in database.

**Comment by KevinMull** [comment]
Do you need to **JSON.stringify** the desin before saving it to the db?
When i try to save it as a plain design it just adds a NULL to the field in the db but when I use STRINGIFY it saves it ok but I cannot load it back.
Probably because in using a VARCHAR(MAX) in SQL SERVER.
Should i be using a varbinary(max) to save the design?
