### ISSUE TITLE
v0.5.0 no longer working in Electron

### ISSUE THREAD

**Issue by derek-groupmail** [unlayer/react-email-editor#11]
Hi,
Since upgrading to v0.5.0 from v0.3.0, the react-email-editor no longer loads the editor.

In the console, I get this error :- 
`Not allowed to load local resource: file://editor.unlayer.com/editor.html`

I'm embedding this within an electron app (v1.7.2), which, if you're unfamiliar with that environment, essentially combines node + chrome.

If I Downgrade back to v0.3.0 then everything loads up fine once more.

What has changed from v0.3.0 to v0.5.0 - I don't see any change/release history.

Any ideas on how to get the latest version to work?

**Comment by derek-groupmail** [comment]
Just some additional information. It appears that in v0.3.0, the component loads the library at `https://designer.unroll.io/assets/embed.bundle.js` which contains this src link `e.src="https://designer.unroll.io/editor"` which works fine.

However, in v0.5.0, the component loads the library at `https://editor.unlayer.com/embed.js` which contains this src link `e.src="//editor.unlayer.com/editor.html"` which doesn't work in electron because the protocol is missing. I assume that this was omitted to allow the link to work with whatever the current protocol is (and assumes either http or https) however, in electron this link defaults to using the 'file' protocol, and therefore doesn't work, in my electron app at least, and possibly every one else's too!

Is there a workaround for this?

**Comment by adeelraza** [comment]
@derek-groupmail we have enforced https now. Can you try again?

**Comment by synapseradio** [comment]
Hi, this is broken for me as well, due to the same issue. However, I do not have an option to roll back, as that seems to break functionality around the editor such as loading templates. That being said, v0.3.0 does seem to actually load.

for v0.5.0, I'm getting an error
    cannot read property 'render' of undefined

that leads to the same html file referenced above.

I am not developing for electron; I am developing for web. It's broken on localhost ( non-https ) and on a live server with https. I reinstalled dependencies to see if forcing to https may fix it, but that doesn't seem to do the trick.

**Comment by adeelraza** [comment]
@synapseradio can you show a code sample?
