### ISSUE TITLE
window is not defined error with Remix 2.0

### ISSUE THREAD

**Issue by wdj82** [unlayer/react-email-editor#364]
Trying to upgrade my project to remix 2.0. In remix 1.8 I have no problem with react-email-editor v1.7.7.

Upgrading to remix 2.0 I'm getting the following error:
![image](https://github.com/unlayer/react-email-editor/assets/37749088/cbdcabc7-3129-4cb1-a17a-fc921ad984d0)

I get the same error in remix 1.8 with newer versions but not 1.7.7

**Comment by jamiemcconnell** [comment]
It also works on `v1.7.8` on `remix@2.0.1`

**Comment by wdj82** [comment]
I did get it working after more fiddling with remix settings. Seems it has to be set for cjs and not esm.

**Comment by DerJacques** [comment]
I don't think the issue is strictly related to Remix.
The problem was likely introduced in [this commit](https://github.com/unlayer/react-email-editor/commit/5dc630cfd1e3b6b96caeb3e25312dead00e52e11#diff-abeb70d7e4dbe23b0b07413c9828a475400b82d474282290ab70c4f5849b90a1R12) (@brunolemos FYI). 

The problem is that `window.__unlayer_lastEditorId = window.__unlayer_lastEditorId || 0;` is executed as a side effect as soon as the file is _imported_. This breaks SSR for any file that includes `react-email-editor`. 

Going back to version `1.7.8` of `react-email-editor` fixes the problem.

**Comment by hojjatramezani** [comment]
I am using Nextjs version 13.0.0 or 13.4.7.
But there is this problem for me. Both on version react-email-editor 1.7.8 and on version react-email-editor 1.7.9
![2023-12-10 09_00_19-Window](https://github.com/unlayer/react-email-editor/assets/57572775/6afe3f6b-9428-453b-a214-44cbacc9b005)
.
.
This problem occurs when I want to build
