### ISSUE TITLE
Specific Versioning

### ISSUE THREAD

**Issue by bgnlordhelmut** [unlayer/react-email-editor#52]
Would it be possible to potentially add in a versioning parameter into Unlayer to ensure that any updates to the product are not automatically propagated out to implementations that are already using it? For example, we may as developers want to communicate to our users that these changes are in place before they're released so that we can facilitate training or something similar.

**Comment by pmccain226** [comment]
Please look into this. Automatically pushing updates (like you guys did last week) can have a drastic effect on user experience or other dev-related work. Please at least communicate changes or allow us to push it out on our own timeline.

**Comment by adeelraza** [comment]
We usually roll out any new features or changes with flags and turn it off by default. The UI change last week however was an important, and mandatory one because many new upcoming features are dependent on this.

But your point makes a ton of sense and I'll pass this feedback to the team so in future, they can communicate new features or changes more effectively. Thanks!

**Comment by bgnlordhelmut** [comment]
Thanks Adeel.
